### ISSUE TITLE
Adding more value to the treasure books

### ISSUE THREAD

**Issue by SongSystem** [Cycro54/Ars_Mage_Fight#3]
Would it be possible to add an option in the config so that the purple cover treasure spell books can ignore the need to add all the glyphs to use them?

**Comment by Cycro54** [comment]
Completely forgot about those actually. Next update I'll set them to be usable regardless if u have the glyphs are not.

**Comment by Cycro54** [comment]
Fixed in 1.16.5-0.6.4
