### ISSUE TITLE
Crash with ring of permanence in inventory

### ISSUE THREAD

**Issue by Umbraminf** [Cycro54/Ars_Mage_Fight#4]
So, my game crashed and your mod was refrenced by the crash report, but honestly, I'm not even shure if it was the cause, sorry about that.
I was swimming and fighting slimes with a sword when it happened, but I have modded armor and curios.
Crash with it equiped:
[crash-2023-11-13_14.04.25-server.txt](https://github.com/Cycro54/Ars_Mage_Fight/files/13339314/crash-2023-11-13_14.04.25-server.txt)

Crash with it only in inventory:
[crash-2023-11-13_15.50.36-server.txt](https://github.com/Cycro54/Ars_Mage_Fight/files/13339319/crash-2023-11-13_15.50.36-server.txt)

I'm using Windows 11 Pro Vers. 22H2
8.00 GB (free: 5.95 GB)
AMD Ryzen 3 3200G with Radeon Vega Graphics       3.60 GHz

**Comment by Cycro54** [comment]
Ty for the report, I'll look into it as soon as possible!

**Comment by Cycro54** [comment]
Fixed in 1.16.5-0.7.0: https://www.curseforge.com/minecraft/mc-mods/ars-mage-fight/files/4884578
If there are any other issues please let meh know
