### ISSUE TITLE
Only the glyph system

### ISSUE THREAD

**Issue by HexDepression** [Cycro54/Ars_Mage_Fight#5]
Hello, I would like to ask a question as I love what your glyphs do but not the system you have in place to collect glyphs, is there anyway to disable the battle table side of the mod?

I tried the config options but sadly it hasn’t worked

**Comment by Cycro54** [comment]
I just tested it and it seems to be working

- Make sure you have the latest version
- Open ars_mage_fight-common.toml with notepad and set Disable_Glyph_System to true
- Save the file and reload minecraft
<img width="960" alt="javaw_6DOYBFes3F" src="https://github.com/user-attachments/assets/4bd78ce4-908f-441d-945c-ce080d66a434">
<img width="960" alt="Notepad_DPInLyQnHg" src="https://github.com/user-attachments/assets/dc6edd44-3f40-49dc-b96f-73da17703e1a">

That said, it seems my Combo glyph is definitely broken. Might fix that later

**Comment by Cycro54** [comment]
Since you haven't responded I'm going to assume you got it working.
Imma close this as completed, ty for giving my mod a try!
